Cast port to int when creating Relay instance
cachewerk/relay pull request #151
Opened 2024-11-21 12:06 UTC by yatsukhnenko

Also added simple integration test

2024-11-21 20:57 UTC, tillkruss requested changes

2024-11-21 20:57 UTC, tillkruss commented on src/Laravel/RelayConnector.php
> +            (int) $config['port'],
Needs to pass php stan validation.

2024-11-22 19:09 UTC, szepeviktor approved these changes

2024-11-22 20:35 UTC, tillkruss approved these changes

2024-11-22 20:36 UTC, merged