fix: end spans in finally block
cachewerk/relay pull request #28
Opened 2022-10-30 10:25 UTC by vmihailenco

Otherwise spans are leaking on exceptions.

2022-10-30 16:04 UTC, tillkruss requested changes

2022-10-30 16:04 UTC, tillkruss commented on src/Psr/Tracing/RelayOpenTelemetry.php
>              $span->recordException($exception)->end();
@vmihailenco: Since we're calling `end()` here, is the `finally` block actually needed?

2022-10-30 17:15 UTC, merged

2022-10-31 06:38 UTC, vmihailenco commented
Completely missed that you have `->end()` after `recordException` :shrug:

2022-10-31 15:43 UTC, tillkruss commented
> Completely missed that you have `->end()` after `recordException` 🤷

Your code style was a lot cleaner tho.